;; Copyright (c) 2021 by Gregor Klinke
;; All rights reserved.

(import (srfi 28))

(define (inherited-above?) (%inherited 'above?))
(define (inherited-asis-wrap-indent) (%inherited 'asis-wrap-indent))
(define (inherited-background-color) (%inherited 'background-color))
(define (inherited-background-tile) (%inherited 'background-tile))
(define (inherited-below?) (%inherited 'below?))
(define (inherited-bottom-margin) (%inherited 'bottom-margin))
(define (inherited-box-corner-radius) (%inherited 'box-corner-radius))
(define (inherited-box-corner-rounded?) (%inherited 'box-corner-rounded?))
(define (inherited-class) (%inherited 'class))
(define (inherited-color) (%inherited 'color))
(define (inherited-end-indent) (%inherited 'end-indent))
(define (inherited-end-margin) (%inherited 'end-margin))
(define (inherited-field-align) (%inherited 'field-align))
(define (inherited-field-width) (%inherited 'field-width))
(define (inherited-first-line-start-indent) (%inherited 'first-line-start-indent))
(define (inherited-font-caps) (%inherited 'font-caps))
(define (inherited-font-name) (%inherited 'font-name))
(define (inherited-font-posture) (%inherited 'font-posture))
(define (inherited-font-size) (%inherited 'font-size))
(define (inherited-font-weight) (%inherited 'font-weight))
(define (inherited-footer-margin) (%inherited 'footer-margin))
(define (inherited-gutter-width) (%inherited 'gutter-width))
(define (inherited-header-margin) (%inherited 'header-margin))
(define (inherited-inhibit-line-breaks?) (%inherited 'inhibit-line-breaks?))
(define (inherited-language) (%inherited 'language))
(define (inherited-last-line-end-indent) (%inherited 'last-line-end-indent))
(define (inherited-left-margin) (%inherited 'left-margin))
(define (inherited-line-number-side) (%inherited 'line-number-side))
(define (inherited-line-spacing) (%inherited 'line-spacing))
(define (inherited-line-thickness) (%inherited 'line-thickness))
(define (inherited-lines) (%inherited 'lines))
(define (inherited-numbered-lines?) (%inherited 'numbered-lines?))
(define (inherited-page-height) (%inherited 'page-height))
(define (inherited-page-width) (%inherited 'page-width))
(define (inherited-position-point-shift) (%inherited 'position-point-shift))
(define (inherited-quadding) (%inherited 'quadding))
(define (inherited-right-margin) (%inherited 'right-margin))
(define (inherited-start-indent) (%inherited 'start-indent))
(define (inherited-start-margin) (%inherited 'start-margin))
(define (inherited-text) (%inherited 'text))
(define (inherited-top-margin) (%inherited 'top-margin))
(define (inherited-whitespace-treatment) (%inherited 'whitespace-treatment))

